(() => {
'use strict';
const model = JSON.parse(document.getElementById('report-data').textContent);
const app = document.getElementById('app');
const NS = 'http://www.w3.org/2000/svg';
function el(tag, text, attrs = {}) { const n = document.createElement(tag); if (text !== undefined && text !== null) n.textContent = String(text); for (const [k,v] of Object.entries(attrs)) n.setAttribute(k,String(v)); return n; }
function svg(tag, attrs = {}, text) { const n = document.createElementNS(NS,tag); for (const [k,v] of Object.entries(attrs)) n.setAttribute(k,String(v)); if(text !== undefined)n.textContent=String(text); return n; }
function showFailure(){let notice=document.getElementById('report-error');if(!notice){notice=el('div',null,{id:'report-error',role:'alert',class:'notice report-error',tabindex:'-1'});document.body.append(notice);}notice.replaceChildren(el('p','That action could not finish. Your saved files have not been changed. Please try again. If you added memories, use Save annotations or Show JSON backup before reloading.'),button('Dismiss message',()=>notice.remove()));notice.focus();}
window.addEventListener('error',()=>showFailure());
window.addEventListener('unhandledrejection',()=>showFailure());
function button(text, action, attrs={}) { const b=el('button',text,{type:'button',...attrs}); b.addEventListener('click',event=>{try{Promise.resolve(action(event)).catch(()=>showFailure());}catch{showFailure();}}); return b; }
function section(id, eyebrow, title, intro) { const s=el('section',null,{id}); s.append(el('p',eyebrow,{class:'eyebrow'}),el('h2',title),el('p',intro,{class:'intro'})); app.append(s); return s; }
function date(t, full=false) { if(!t)return 'Not recorded'; return new Intl.DateTimeFormat('en-AU',{timeZone:model.metadata.timeZone,day:'numeric',month:'long',year:'numeric',...(full?{hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}:{})}).format(new Date(t)); }
function format(n){return Number(n).toLocaleString('en-AU');}
function chart(width,height,label) {const s=svg('svg',{viewBox:`0 0 ${width} ${height}`,role:'img','aria-label':label}); s.append(svg('title',{},label));return s;}
const mast=el('header',null,{class:'masthead'});mast.append(el('a','HINDSIGHT',{href:'#top',class:'wordmark'}),el('span','LOCAL / PERSONAL',{class:'local-badge'}));app.append(mast);
const hero=el('section',null,{id:'top',class:'hero'});hero.append(el('p','YOUR RECORDED HISTORY',{class:'eyebrow'}),el('h1','A place to remember.'),el('p','Recorded actions can bring a period back to mind. The dates and meaning of your life remain yours.',{class:'lead'}));
const coverage=el('div',null,{class:'coverage'});coverage.append(el('strong','Recorded actions covered'),el('p',`${date(model.metadata.first,true)} — ${date(model.metadata.last,true)} · ${model.metadata.timeZone} (UTC+10; times are local)`),el('p',`${model.metadata.timeZone} (UTC+10). Supplied export date: ${model.metadata.exportDate}; export time unknown.`),el('p',(model.metadata.last&&new Date(model.metadata.last).toISOString().slice(0,10)!==new Intl.DateTimeFormat('en-CA',{timeZone:model.metadata.timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(model.metadata.last))?'The latest action falls on the following local day because its stored time is UTC. ':'')+'These are observed bounds, not complete coverage of the time between them.'));
hero.append(coverage,el('p',`${format(model.observations)} retained observations · ${model.metadata.parseStatus==='partial'?'Some export records could not be included.':'The available export records were processed.'} This personal report reveals creator/folder identities and may reveal interests, beliefs and affiliations.`,{class:'small'}));app.append(hero);
const nav=el('nav',null,{'aria-label':'Report sections'});for(const [id,label] of [['activity','Saving & liking'],['creators','Creators over time'],['folders','Recent folders'],['no-primary','Other saving patterns'],['memories','Your memories']])nav.append(el('a',label,{href:'#'+id}));app.append(nav);
const activity=section('activity','01 / RECORDED ACTIONS','Saving and liking changed.','Two kinds of recorded action, shown separately. Nothing here tells us why they changed.');
const facts=el('div',null,{class:'facts'});for(const year of [2021,2026]){const y=model.years.find(x=>x.year===year);if(!y)continue;const c=el('div',null,{class:'fact'});c.append(el('span',`${year}${y.partial?' · partial year':''}`,{class:'eyebrow'}),el('strong',`${format(y.saved)} saves`),el('strong',`${format(y.liked)} likes`));facts.append(c);}activity.append(facts,el('p','Annual counts use UTC calendar years. The first and final years are partial; 2026 is not a full-year comparison or an annualised estimate.',{class:'small'}));
const annual=chart(1000,model.years.length*68+35,'Annual saved and liked action counts. Expand the year rows below for exact monthly counts.');
const max=Math.max(1,...model.years.flatMap(y=>[y.saved,y.liked]));
model.years.forEach((y,i)=>{const yy=i*68+25;annual.append(svg('text',{x:0,y:yy+10,class:'axis'},`${y.year}${y.partial?' *':''}`));for(const [ch,dy,col] of [['saved',0,'#236759'],['liked',25,'#ad623c']]){const w=y[ch]/max*700;annual.append(svg('rect',{x:88,y:yy+dy,width:Math.max(w,y[ch]?1:0),height:15,fill:col,rx:2}));annual.append(svg('text',{x:96+w,y:yy+dy+12,class:'axis'},`${format(y[ch])} ${ch==='saved'?'saves':'likes'}`));}});activity.append(annual);
const months=el('details');months.append(el('summary','Explore monthly counts'));for(const y of model.years){const d=el('details');d.append(el('summary',`${y.year}${y.partial?' — partial observed year':''}`));const table=el('table');const h=el('tr');['Month (UTC)','Saved','Liked'].forEach(t=>h.append(el('th',t)));table.append(h);for(const m of y.months){const r=el('tr');const start=Date.UTC(y.year,m.month-1,1),end=Date.UTC(y.year,m.month,1),outside=!model.metadata.first||end<=Date.parse(model.metadata.first)||start>Date.parse(model.metadata.last),partial=!outside&&(start<Date.parse(model.metadata.first)||end>Date.parse(model.metadata.last));r.append(el('td',`${y.year}-${String(m.month).padStart(2,'0')}${outside?' — outside observed bounds':partial?' — partial':''}`),el('td',outside?'—':m.saved),el('td',outside?'—':m.liked));table.append(r);}d.append(table);months.append(d);}activity.append(months);

const creatorSection=section('creators','02 / THE MULTI-YEAR BACKBONE','Creators across the years.','A mark means a retained action in that month. Space between marks is not evidence of an ended relationship or an absence elsewhere.');
const historyTrack=el('div',null,{class:'annotation-track','aria-label':'Memories on the multi-year timeline'});creatorSection.append(historyTrack);
const creatorTools=el('div',null,{class:'toolbar'}),channel=el('select',null,{'aria-label':'Creator channel'}),search=el('input',null,{type:'search',placeholder:'Find a recorded creator','aria-label':'Find a recorded creator'});
for(const ch of ['combined','saved','liked'])channel.append(el('option',ch,{value:ch}));creatorTools.append(el('label','Channel '),channel,search);creatorSection.append(creatorTools);
const creatorCount=el('p',null,{class:'small'}),creatorRows=el('div'),creatorPanel=el('div');creatorSection.append(creatorCount,el('p','Green upper marks: saved · Terracotta lower marks: liked. Order: active months, active weeks, then sessions.',{class:'small'}),creatorRows,creatorPanel);
let creatorLimit=20;
function axis(s,range,y){for(let year=new Date(range.start).getUTCFullYear();year<=new Date(range.end-1).getUTCFullYear();year++){const x=(Date.UTC(year,0,1)-range.start)/(range.end-range.start)*1000;s.append(svg('line',{x1:x,x2:x,y1:y+5,y2:y+12,stroke:'#b6c1b6'}),svg('text',{x:x+3,y,class:'axis'},year));}}
function technicalDetail(value){const d=el('details');d.append(el('summary','Technical detail'),el('pre',JSON.stringify(value,null,2)));return d;}
function openEvidence(target,box){const origin=document.activeElement;const close=()=>{target.replaceChildren();if(origin?.isConnected){origin.focus();origin.scrollIntoView({block:'nearest'});}};box.prepend(button('Close evidence — back to timeline',close));box.addEventListener('keydown',event=>{if(event.key==='Escape'&&!document.querySelector('dialog[open]')){event.preventDefault();close();}});target.replaceChildren(box);box.focus();box.scrollIntoView({block:'nearest'});}
function creatorDetail(r){const box=el('div',null,{class:'panel',tabindex:'-1'});box.append(el('h3',r.creatorRef.creatorId),el('p',`${r.observationCount} recorded actions on ${r.distinctDays} local dates, spread across ${r.activeMonths} months.`),el('p',`First recorded: ${date(r.firstRecorded,true)}. Last recorded here: ${date(r.lastRecorded,true)}.`),el('p',`The busiest recorded 28 days contained ${r.peakWindow.observations} actions, ending ${date(r.peakWindow.endInclusive)}.`));
const win=r.monthlyWindows.at(-1);if(win)box.append(el('p',`In the latest twelve-month view, actions appear in ${win[1]} months. The available record may not cover the whole period.`));
for(const w of r.followUpWindows)box.append(el('p',`${w.observations} later actions are recorded from ${date(w.start)} up to, but not including, ${date(w.endExclusive)}.`));
const records=el('details');records.append(el('summary',`Recorded dates (${r.records.length})`));const list=el('ul');for(const rec of r.records)list.append(el('li',`${date(rec.time,true)} · ${rec.channel}`));records.append(list);box.append(records,technicalDetail(r));openEvidence(creatorPanel,box);}
function renderCreators(){const data=model.creators.find(c=>c.channel===channel.value);const found=data.rows.filter(r=>r.creatorRef.creatorId.toLocaleLowerCase().includes(search.value.toLocaleLowerCase()));creatorRows.replaceChildren();creatorCount.textContent=`${format(data.rows.length)} creators recorded more than once; ${format(data.singletonCreators)} creators recorded once are counted but not listed; ${data.unknownObservations} actions have no recorded creator name. Showing ${Math.min(creatorLimit,found.length)} of ${found.length} matching rows. Channel observed from ${date(data.coverage.firstRecordedInChannel)} through ${date(data.lastRecorded)}; export date ${date(data.config.asOf)}.`;
for(const r of found.slice(0,creatorLimit)){const row=el('div',null,{class:'lane'});row.append(button(r.creatorRef.creatorId,()=>creatorDetail(r)),el('p',`${r.activeMonths} active months · ${r.activeWeeks} active weeks · Last recorded here: ${date(r.lastRecorded)}`,{class:'small'}));const wrap=el('div',null,{class:'timeline'}),plot=chart(1000,65,`Recorded monthly actions for ${r.creatorRef.creatorId}; gaps are not bridged`);axis(plot,model.historyRange,15);const keys=new Set(r.records.map(e=>e.month+'/'+e.channel));for(const key of keys){const [month,ch]=key.split('/'),t=Date.parse(month+'-15T00:00:00Z'),x=(t-model.historyRange.start)/(model.historyRange.end-model.historyRange.start)*1000;const mark=svg('rect',{x:x-2,y:ch==='saved'?33:45,width:4,height:8,fill:ch==='saved'?'#236759':'#ad623c'});mark.append(svg('title',{},`${month}: ${ch}`));plot.append(mark);}wrap.append(plot);row.append(wrap);creatorRows.append(row);}
if(found.length>creatorLimit)creatorRows.append(button('Show 20 more creators',()=>{creatorLimit+=20;renderCreators();}));}
channel.addEventListener('change',()=>{creatorLimit=20;creatorPanel.replaceChildren();renderCreators();});search.addEventListener('input',()=>{creatorLimit=20;renderCreators();});renderCreators();

const folderSection=section('folders','03 / RECENT CURRENT FOLDERS','Concentrations worth revisiting.','Use this view to locate periods to revisit, not to date phases. 1 December 2025–30 August 2026 (UTC window). This is mostly 2026, not the whole history. Current membership is grouped by save date, not the date something was filed.');
folderSection.append(el('p','The week beginning 24 August 2026 is unassessed because the export time is unknown. Collection-creation weeks and earlier history are also unassessed. Axis bins start on Monday UTC (10:00 in Brisbane).',{class:'notice'}));
const legend=el('div',null,{class:'legend','aria-label':'How to read the three agreement tiers'});
for(const [key,tier,label,meaning] of [['exact','exact-stable','Solid','Dates hold across all nine settings; they are not verified personal dates.'],['overlap','overlap-stable','Faded','The concentration overlaps across all settings, but its edges can move by up to ten weeks.'],['primary','primary-only','Stippled','Appears in some settings only.']]){const item=el('div',null,{class:'legend-item'});item.append(el('span',null,{class:'legend-swatch '+tier,'aria-hidden':'true'}),el('strong',`${model.tiers[key]} · ${label}`),el('p',meaning));legend.append(item);}
folderSection.append(legend,el('p',`${model.tiers.exact+model.tiers.overlap} periods overlap in all nine settings, including the ${model.tiers.exact} periods with unchanged dates. These styles show how the nine calculations differ, not the chance that a personal phase occurred.`,{class:'small'}));
const folderTrack=el('div',null,{class:'annotation-track','aria-label':'Memories on the recent-folder timeline'});folderSection.append(folderTrack);
const nested=el('input',null,{type:'checkbox',id:'nested'}),nestedLabel=el('label',' Show shorter concentrations within these periods');nestedLabel.prepend(nested);folderSection.append(nestedLabel);
const folderRows=el('div'),folderPanel=el('div');folderSection.append(folderRows,folderPanel);let shapeId=0;
const X=t=>(t-model.folderRange.start)/(model.folderRange.end-model.folderRange.start)*1000;
function folderAxis(plot){for(let t=Date.UTC(2025,11,1);t<model.folderRange.end;){plot.append(svg('text',{x:X(t)+2,y:13,class:'axis'},new Intl.DateTimeFormat('en',{timeZone:'UTC',month:'short'}).format(t)));const d=new Date(t);t=Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,1);}}
function shape(plot,bar,y){const id='shape-'+shapeId++, defs=svg('defs');plot.append(defs);const groups=[];let current=[];for(const cell of bar.cells){if(cell.assessed&&cell.votes>0){if(current.length&&cell.time-current.at(-1).time!==604800000){groups.push(current);current=[];}current.push(cell);}else if(current.length){groups.push(current);current=[];}}if(current.length)groups.push(current);
for(const [gi,cells] of groups.entries()){const start=cells[0].time,end=cells.at(-1).time+604800000,x=X(start),width=X(end)-x;if(bar.tier==='exact-stable'){plot.append(svg('rect',{x,y,width,height:14,fill:'#153c32',stroke:'#153c32','data-tier':bar.tier}));continue;}
const gid=id+'-'+gi,gradient=svg('linearGradient',{id:gid,x1:'0%',x2:'100%'}),colour=bar.tier==='overlap-stable'?'#89998d':'#202b26';
const e=bar.envelope,fadeIn=Math.max(0.5*604800000,e.latestStart-e.earliestStart),fadeOut=Math.max(0.5*604800000,e.latestEnd-e.earliestEnd);
gradient.append(svg('stop',{offset:'0%','stop-color':colour,'stop-opacity':0}));
for(const c of cells){for(const fraction of [0.1,0.5,0.9]){const t=c.time+fraction*604800000,alpha=Math.min(1,(t-start)/fadeIn,(end-t)/fadeOut)*(0.55+0.45*c.votes/9);gradient.append(svg('stop',{offset:((t-start)/(end-start)*100)+'%','stop-color':colour,'stop-opacity':Math.max(0,alpha)}));}}
gradient.append(svg('stop',{offset:'100%','stop-color':colour,'stop-opacity':0}));defs.append(gradient);
if(bar.tier==='overlap-stable'){plot.append(svg('rect',{x,y,width,height:14,fill:`url(#${gid})`,'data-tier':bar.tier}));}
else{const pattern=svg('pattern',{id:gid+'-dots',width:7,height:7,patternUnits:'userSpaceOnUse'});pattern.append(svg('circle',{cx:2,cy:2,r:1.8,fill:'#202b26'}));const mask=svg('mask',{id:gid+'-mask',maskUnits:'userSpaceOnUse',x,y,width,height:14,style:'mask-type:alpha'});mask.append(svg('rect',{x,y,width,height:14,fill:`url(#${gid})`}));defs.append(pattern,mask);plot.append(svg('rect',{x,y,width,height:14,fill:`url(#${gid}-dots)`,mask:`url(#${gid}-mask)`,'data-tier':bar.tier}));}
}}
function rateDescription(observed,baseline){if(!Number.isFinite(observed)||!Number.isFinite(baseline)||baseline<=0)return 'There is not enough information to compare this folder with its usual share of your saves.';const ratio=observed/baseline;if(ratio<0.5)return 'Less than half the usual share of your saves went into this folder.';if(ratio<1.5)return 'About the usual share of your saves went into this folder.';return `About ${Math.round(ratio)} times the usual share of your saves went into this folder.`;}
function folderDetail(folder,bar){const box=el('div',null,{class:'panel',tabindex:'-1'});box.append(el('h3',folder.name),el('p',rateDescription(bar.observedFraction,bar.baselineFraction)),el('p','Here, “usual” means this folder’s share of saves across the surrounding weeks used for this calculation, not saves per day.'),el('p',`${bar.observations} saves in this folder, on ${bar.activeDays} local dates across ${bar.activeWeeks} weeks.`),el('p',bar.tier==='exact-stable'?'The same dates appear in all nine versions of the calculation.':bar.tier==='overlap-stable'?'All nine versions find an overlapping period, but the edges move.':`An overlapping period appears in ${bar.overlap} of nine versions of the calculation.`),el('p',`Suggested starts range from ${date(bar.envelope.earliestStart)} to ${date(bar.envelope.latestStart)}; suggested last days range from ${date(bar.envelope.earliestEnd-1)} to ${date(bar.envelope.latestEnd-1)}. These are prompts for memory, not confirmed dates from your life.`),el('p',bar.secondaryExact?'Counting only saves placed in folders gives the same dates.':bar.secondaryOverlap?'Counting only saves placed in folders finds an overlapping period.':'Counting only saves placed in folders does not find an overlapping period.'),el('p',bar.touchesSpanStart||bar.touchesSpanEnd?'This period reaches the edge of the weeks we can assess, so its beginning or end may extend beyond the available evidence.':'There are assessable weeks on both sides of this period.'),el('p','A save date does not tell us when you put something in this folder. Similar results across calculations do not establish a lived phase.'));
box.append(button('Add a memory here',()=>openMemory(null,bar.envelope)),technicalDetail(bar));openEvidence(folderPanel,box);}
function renderFolders(){folderRows.replaceChildren();for(const folder of model.folders.filter(f=>f.bars.some(b=>b.level===1))){const bars=folder.bars.filter(b=>nested.checked||b.level===1),row=el('div',null,{class:'lane'});row.append(el('h3',folder.name));const plot=chart(1000,40+bars.length*26,`${folder.name}: ${bars.map(b=>b.tier==='exact-stable'?'solid':b.tier==='overlap-stable'?'faded':'stippled').join(', ')}. Hatched weeks are unassessed.`);folderAxis(plot);const defs=svg('defs'),pid='gap-'+shapeId++;const pattern=svg('pattern',{id:pid,width:7,height:7,patternUnits:'userSpaceOnUse'});pattern.append(svg('path',{d:'M0 7L7 0',stroke:'#bbc3b7','stroke-width':1}));defs.append(pattern);plot.append(defs);for(const w of folder.weeks.filter(w=>w.status!=='assessed')){const t=Date.parse(w.week);plot.append(svg('rect',{x:X(t),y:23,width:X(t+604800000)-X(t),height:bars.length*26+5,fill:`url(#${pid})`,'data-unassessed':w.week}));}bars.forEach((b,i)=>shape(plot,b,28+i*26));const wrap=el('div',null,{class:'timeline'});wrap.append(plot);row.append(wrap);const controls=el('div',null,{class:'toolbar'});bars.forEach(b=>controls.append(button(`${b.tier==='exact-stable'?'=':b.tier==='overlap-stable'?'≈':'⋯'} ${b.tier==='exact-stable'?'Solid':b.tier==='overlap-stable'?'Faded':'Stippled'} · ${b.tier==='exact-stable'?b.startWeek:b.overlap+' of 9 calculations'}${b.level>1?' · shorter concentration':''}`,()=>folderDetail(folder,b))));row.append(controls);folderRows.append(row);}}
nested.addEventListener('change',renderFolders);renderFolders();
const noSection=section('no-primary','04 / OTHER RECORDED PATTERNS','Other saving patterns.','These folders have saves, but no concentration in the main view. Some recur across weeks; others have sparse or newly available history. That does not tell us the interest was steady.');
const noFolders=model.folders.filter(f=>!f.bars.some(b=>b.level===1));noSection.append(el('p',`${noFolders.length} folders · ${noFolders.filter(f=>f.summary.otherSettings.length).length} show a concentration in another calculation · ${noFolders.filter(f=>!f.summary.assessedWeeks).length} have no weeks we can assess. These groups overlap.`,{class:'small'}));
for(const folder of noFolders){const row=el('details',null,{'data-no-primary':folder.id});row.append(el('summary',folder.name));const s=folder.summary;row.append(el('p',`Folder created: ${date(folder.createdAt)}. Saves in this view: ${s.records}. We could use ${s.eligibleRecords} to look for concentrations; ${s.excludedRecords} fell outside the weeks we could assess. ${s.unmatched} folder entries have no matching saved record.`),el('p',`${s.assessedWeeks?s.activeWeeks+' active weeks out of '+s.assessedWeeks+' assessed weeks':'Not assessed yet'} · ${s.distinctDays} active local dates · ${s.activeMonths} active months.`),el('p',`First recorded save in this window: ${date(s.first)}. Last recorded here: ${date(s.last)}.`));const plot=chart(1000,80,`${folder.name}: weekly saves; circles at the baseline mean observed zero, crossed cells mean unassessed`);folderAxis(plot);const max=Math.max(1,...folder.weeks.map(w=>w.numerator));for(const w of folder.weeks){const x=X(Date.parse(w.week)),width=X(Date.parse(w.week)+604800000)-x-3;if(w.status!=='assessed'){plot.append(svg('path',{d:`M${x} 30l${width} 35m0 -35l${-width} 35`,stroke:'#bcc3b8','stroke-width':1}));}if(w.numerator)plot.append(svg('rect',{x,y:70-w.numerator/max*42,width,height:w.numerator/max*42,fill:w.status==='assessed'?'#617e69':'#acb8a7'}));else if(w.status==='assessed')plot.append(svg('circle',{cx:x+width/2,cy:68,r:2,fill:'#617e69'}));}row.append(plot,el('p','Discrete weekly counts; observed zero is a dot; weeks we cannot assess are crossed. We do not assume an interest continued between recorded saves.',{class:'small'}));if(s.otherSettings.length){row.append(el('p',`A concentration appears in ${s.otherSettings.length} other calculations. It remains separate from the main timeline.`));const d=el('details');d.append(el('summary','Technical detail'),el('pre',JSON.stringify(s.otherSettings,null,2)));row.append(d);}noSection.append(row);}

const A=globalThis.HindsightAnnotations;
let annotations;
try{annotations=A.validate(JSON.parse(document.getElementById('annotation-data').textContent));}catch{annotations={format:'hindsight.annotations',schemaVersion:1,revision:0,sensitivity:'personal',events:[]};app.append(el('p','The embedded annotations were invalid and were not loaded. The original file has not been changed.',{class:'notice'}));}
let dirty=false;
const memories=section('memories','05 / YOUR WORDS','What comes back to mind?','Add a memory, a date you know, or a period you remember approximately. Nothing here is written or interpreted for you.');
const memoryTools=el('div',null,{class:'toolbar'}),memoryStatus=el('p','No unsaved annotation changes.',{class:'status',role:'status'}),memoryCards=el('div');
function download(content,name,type){const u=URL.createObjectURL(new Blob([content],{type}));const a=el('a',null,{href:u,download:name});document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),2000);}
function savedNotice(){dirty=false;memoryStatus.textContent='Download requested. Check that your browser saved the file; this tab cannot confirm where it was stored.';}
const input=el('input',null,{type:'file',accept:'.json,application/json','aria-label':'Import annotation bundle'});input.hidden=true;
memoryTools.append(button('Add a memory',()=>openMemory()),button('Save annotations',()=>{download(JSON.stringify(annotations,null,2),'hindsight-annotations.json','application/json');savedNotice();}),button('Import annotations',()=>input.click()),button('Show JSON backup',()=>{const backup=el('dialog',null,{'aria-label':'Annotation JSON backup'});backup.append(el('h3','Annotation JSON backup'),el('p','Copy this text into a UTF-8 .json file if your browser does not save downloads. It includes personal memories and their recording context.'));const area=el('textarea',JSON.stringify(annotations,null,2),{readonly:'',rows:14,'aria-label':'Annotation JSON'});backup.append(area,button('Close',()=>{backup.close();backup.remove();}));document.body.append(backup);backup.showModal();area.focus();area.select();}),button('Save personal HTML copy',()=>{const copy=document.documentElement.cloneNode(true);copy.querySelector('#app').replaceChildren();copy.querySelectorAll('dialog').forEach(d=>d.remove());copy.querySelector('#annotation-data').textContent=JSON.stringify(annotations).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026');download('<!doctype html>\n'+copy.outerHTML,'hindsight-personal.html','text/html');savedNotice();}),button('Print report',()=>window.print()),input);memories.append(memoryTools,el('p','Saved HTML includes your recorded creator/folder identities and memories. Both exports are personal. Keep them only where you intend; no automatic browser storage is used.',{class:'small'}),memoryStatus,memoryCards);
input.addEventListener('change',async()=>{try{const file=input.files?.[0];if(!file)return;if(file.size>2*1024*1024)throw Error('The annotation file exceeds the 2 MiB import limit.');const incoming=JSON.parse(await file.text());annotations=A.merge(annotations,incoming);dirty=true;memoryStatus.textContent='Imported locally. Save a copy to keep these memories.';renderMemories();}catch(e){memoryStatus.textContent=e instanceof SyntaxError?'That file is not valid JSON. No memories were changed.':String(e.message||'Import could not finish. No memories were changed.');}finally{input.value='';}});
const dialog=el('dialog',null,{'aria-labelledby':'memory-title'}),form=el('form');dialog.append(form);document.body.append(dialog);let editingId=null;let memoryOrigin=null;
function inputField(label,name,type='text'){const l=el('label',label),i=el('input',null,{name,type});l.append(i);form.append(l);return i;}
form.append(el('h2','Add a memory',{id:'memory-title'}),el('p','Recorded after viewing evidence. Dates are yours to change or leave approximate.',{class:'context'}));
const labelInput=inputField('Your title','label');labelInput.maxLength=200;labelInput.required=true;
const kindLabel=el('label','Memory type'),kind=el('select',null,{name:'kind'});kind.append(el('option','Period',{value:'period'}),el('option','Point in time',{value:'point'}));kindLabel.append(kind);form.append(kindLabel);
const startEarliest=inputField('Start — earliest possible date','start-earliest','date'),startLatest=inputField('Start — latest possible date','start-latest','date');startEarliest.required=true;startLatest.required=true;
const unknownLabel=el('label',' End unknown / open'),unknown=el('input',null,{type:'checkbox',name:'end-unknown'});unknownLabel.prepend(unknown);form.append(unknownLabel);
const endEarliest=inputField('End — earliest possible date','end-earliest','date'),endLatest=inputField('End — latest possible date','end-latest','date');
const precisionLabel=el('label','Date precision'),precision=el('select',null,{name:'precision'});for(const p of ['day','month','year','approximate'])precision.append(el('option',p,{value:p}));precisionLabel.append(precision);form.append(precisionLabel);
const noteLabel=el('label','Your notes (optional)'),notes=el('textarea',null,{name:'notes',maxlength:10000});noteLabel.append(notes);form.append(noteLabel);const formError=el('p',null,{role:'alert',class:'notice'});formError.hidden=true;form.append(formError);
const actions=el('div',null,{class:'toolbar'}),submit=el('button','Keep memory',{type:'submit'});actions.append(submit,button('Cancel',()=>dialog.close()));form.append(actions);
function endState(){const disabled=kind.value==='point'||unknown.checked;endEarliest.disabled=disabled;endLatest.disabled=disabled;endEarliest.required=!disabled;endLatest.required=!disabled;unknown.disabled=kind.value==='point';}
kind.addEventListener('change',endState);unknown.addEventListener('change',endState);
function calendarDay(t){if(t===undefined||t===null||t===''||!['string','number'].includes(typeof t))return '';try{const value=new Date(t);if(!Number.isFinite(value.getTime()))return '';return new Intl.DateTimeFormat('en-CA',{timeZone:model.metadata.timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).format(value);}catch{return '';}}
function inclusiveEnd(t){if(!calendarDay(t))return '';return calendarDay(new Date(t).getTime()-1);}
function openMemory(record=null,envelope=null){
memoryOrigin=document.activeElement;
try{if(!dialog.open)dialog.showModal();}catch{showFailure();return;}
try{
editingId=record?.id??null;form.reset();formError.hidden=true;form.querySelector('h2').textContent=record?'Edit your memory':'Add a memory';form.querySelector('.context').textContent=record?`${A.context(record.recordedContext)}. This edit will be marked after viewing evidence.`:'Recorded after viewing evidence. Suggested dates show the range found by the calculations, not dates you have confirmed.';
labelInput.value=record?.label??'';kind.value=record?.kind??'period';notes.value=record?.notes??'';precision.value=record?.start?.precision??'approximate';
startEarliest.value=record?.start?.earliest??(envelope?calendarDay(envelope.earliestStart):'');startLatest.value=record?.start?.latest??(envelope?calendarDay(envelope.latestStart):'');endEarliest.value=record?.end?.earliest??(envelope?inclusiveEnd(envelope.earliestEnd):'');endLatest.value=record?.end?.latest??(envelope?inclusiveEnd(envelope.latestEnd):'');unknown.checked=record?record.end===null:!endEarliest.value||!endLatest.value;
if(envelope&&[startEarliest,startLatest,endEarliest,endLatest].some(field=>!field.value)){formError.hidden=false;formError.textContent='Some suggested dates were unavailable. You can still add your memory: enter the dates you remember, or leave the end unknown.';}
endState();labelInput.focus();
}catch{formError.hidden=false;formError.textContent='The suggested details could not be filled in. Please close this window and use Add a memory in section 05 to enter your own dates. Your saved files have not been changed.';}
}
form.addEventListener('submit',event=>{event.preventDefault();try{const old=annotations.events.find(e=>e.id===editingId);const memoryId=editingId??crypto.randomUUID();annotations=A.upsert(annotations,{kind:kind.value,label:labelInput.value,start:{earliest:startEarliest.value,latest:startLatest.value,precision:precision.value},end:kind.value==='point'||unknown.checked?null:{earliest:endEarliest.value,latest:endLatest.value,precision:precision.value},timezone:old?.timezone??model.metadata.timeZone,notes:notes.value},{id:memoryId,now:new Date().toISOString(),snapshotId:model.metadata.snapshotId});dirty=true;memoryStatus.textContent='Unsaved memories — save annotations or a personal HTML copy before closing.';renderMemories();dialog.close();confirmMemory(memoryId);}catch(e){if(dialog.open){formError.hidden=false;formError.textContent=e.message;}else showFailure();}});
function confirmMemory(id){const notice=el('div',null,{class:'notice memory-confirmation',role:'status',tabindex:'-1'});notice.append(el('p','Your memory is now in this report. Save annotations or a personal HTML copy to keep it after closing.'),button('Go to this memory',()=>{const card=document.getElementById('memory-'+id);if(card){card.scrollIntoView({block:'center'});card.focus();}}));document.querySelectorAll('.memory-confirmation').forEach(n=>n.remove());if(memoryOrigin?.isConnected)memoryOrigin.insertAdjacentElement('afterend',notice);else memoryTools.append(notice);notice.focus();notice.scrollIntoView({block:'nearest'});}
function localMidnight(day,timezone){const target=Date.parse(day+'T00:00:00Z');let t=target;const f=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'});for(let i=0;i<4;i++){const p=Object.fromEntries(f.formatToParts(t).filter(p=>p.type!=='literal').map(p=>[p.type,Number(p.value)]));const delta=target-Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second);t+=delta;if(!delta)break;}return t;}
function annotationTrack(target,range){target.replaceChildren(el('strong','Your memories on this timeline'));const visible=annotations.events.filter(e=>localMidnight(e.start.earliest,e.timezone)<range.end&&localMidnight(e.end?.latest??e.start.latest,e.timezone)>=range.start);if(!visible.length){target.append(el('p','No memories added in this view yet.',{class:'small'}));return;}
for(const e of visible){const row=el('div',null,{class:'annotation-card'});row.append(button(e.label,()=>openMemory(e)),el('p',A.context(e.recordedContext),{class:'context'}));if(e.lastEditedContext==='after-viewing-evidence')row.append(el('p','Edited after viewing evidence',{class:'context'}));const start=localMidnight(e.start.earliest,e.timezone),latestStart=localMidnight(e.start.latest,e.timezone),end=localMidnight(e.end?.latest??e.start.latest,e.timezone),earliestEnd=e.end?localMidnight(e.end.earliest,e.timezone):null;const xx=t=>Math.max(0,Math.min(1000,(t-range.start)/(range.end-range.start)*1000));const plot=chart(1000,38,`${e.label}; user-authored; ${A.context(e.recordedContext)}; ${e.end?'uncertain bounds shown':'end unknown or point'}`);
if(e.kind==='point'&&e.start.earliest===e.start.latest)plot.append(svg('path',{d:`M${xx(start)} 10l6 8l-6 8l-6 -8z`,fill:'#846640'}));else{plot.append(svg('path',{d:`M${xx(start)} 10v16m0 -8H${xx(latestStart)}`,stroke:'#846640',fill:'none','stroke-width':2}));if(e.end){plot.append(svg('path',{d:`${earliestEnd>=latestStart?`M${xx(latestStart)} 18H${xx(earliestEnd)}`:''}M${xx(earliestEnd)} 18H${xx(end)}m0 -8v16`,stroke:'#846640',fill:'none','stroke-dasharray':'4 3'}));}else plot.append(svg('text',{x:xx(latestStart)+7,y:23,class:'axis'},e.kind==='point'?'approximate point':'end unknown'));}if(start<range.start)plot.append(svg('text',{x:0,y:35,class:'axis'},'← continues'));if(end>=range.end)plot.append(svg('text',{x:905,y:35,class:'axis'},'continues →'));row.append(plot);target.append(row);}}
function renderMemories(){memoryCards.replaceChildren();for(const e of annotations.events){const c=el('article',null,{class:'annotation-card',id:'memory-'+e.id,tabindex:'-1'});c.append(el('h3',e.label),el('p',A.context(e.recordedContext),{class:'context'}));if(e.lastEditedContext==='after-viewing-evidence')c.append(el('p','Edited after viewing evidence',{class:'context'}));c.append(el('p',`${e.start.earliest}–${e.start.latest} (${e.start.precision})${e.kind==='point'?' · point':e.end?' through '+e.end.earliest+'–'+e.end.latest:' · end unknown'} · ${e.timezone}`),el('p',e.notes),el('p',`Created ${e.createdAt}; updated ${e.updatedAt}; revision ${e.revision}.`,{class:'small'}),button('Edit memory',()=>openMemory(e)));if(e.history.length){const d=el('details');d.append(el('summary',`Earlier revisions (${e.history.length})`));for(const h of e.history)d.append(el('p',`Revision ${h.revision}: ${h.label} · ${h.start.earliest}–${h.start.latest} · ${A.context(h.recordedContext)}${h.lastEditedContext==='after-viewing-evidence'?' · Edited after viewing evidence':''}`),el('p',h.notes));c.append(d);}memoryCards.append(c);}if(!annotations.events.length)memoryCards.append(el('p','No memories added yet. The report is usable without adding any.',{class:'empty'}));annotationTrack(historyTrack,model.historyRange);annotationTrack(folderTrack,model.folderRange);}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});renderMemories();
const methods=section('methods','READING THE EVIDENCE','What this record can and cannot tell you.','Retained actions are incomplete observations. An empty week is not an empty life. No view here establishes complete interests, historical filing dates or personal phase boundaries.');methods.append(el('p',`${model.folders.reduce((n,f)=>n+f.summary.unmatched,0)} folder entries have no matching saved record, so we cannot give them a save date. The retained export is unchanged. Captions and web links are not included in this report.`),el('p','Sessions group nearby actions; they do not measure watching time. The main folder view keeps the calculation chosen before looking at the results. Other calculations remain available for comparison.'),el('p',`Snapshot ${model.metadata.snapshotId}. Report generated ${date(model.metadata.generatedAt,true)}; this is not the data cutoff.`,{class:'small'}));
const provenance=el('details');provenance.append(el('summary','Snapshot and method provenance'),el('pre',JSON.stringify({metadata:model.metadata,sessionSettings:model.creators.map(c=>({channel:c.channel,seconds:c.config.sessionSeconds,basis:c.config.sessionBasis})),tiers:model.tiers},null,2)));methods.append(provenance);
app.append(el('footer','HINDSIGHT · The record supplies evidence. You supply meaning.',{class:'small'}));



})();
