import type { InstagramExploration } from './exploration.ts';

const n = (v: number | null | undefined) => v === null || v === undefined ? 'not available' : Number.isInteger(v) ? v.toLocaleString('en-US') : v.toFixed(2);
const pct = (v: number | null | undefined) => v === null || v === undefined ? 'not available' : `${(v * 100).toFixed(2)}%`;
const escape = (v: unknown) => String(v ?? 'unknown').replace(/[\u0000-\u001f\u007f-\u009f]/gu, ' ').replace(/[&<>|`*_\[\]\\]/gu, ch => `&#${ch.charCodeAt(0)};`);
const table = (heads: string[], rows: unknown[][]) => `| ${heads.join(' | ')} |\n| ${heads.map(() => '---').join(' | ')} |\n${rows.map(row => `| ${row.map(escape).join(' | ')} |`).join('\n')}\n`;

// Explicit projection: no captions, URLs, names, account IDs or literal hashtags.
// Ranks link records only within this report; they do not guarantee anonymity.
export function aggregateExploration(data: InstagramExploration) {
  const tagTotals = new Map<string, number>();
  for (const y of data.years) for (const t of y.channels.combined.hashtags) tagTotals.set(t.tag, (tagTotals.get(t.tag) ?? 0) + t.count);
  const tagRanks = new Map([...tagTotals].sort(([a, n], [b, m]) => m - n || a.localeCompare(b)).map(([t], i) => [t, `H${String(i + 1).padStart(4, '0')}`]));
  const cleanDetail = (d: InstagramExploration['years'][number]['channels']['combined']) => ({ ...d, hashtags: d.hashtags.map(t => ({ tag: tagRanks.get(t.tag)!, count: t.count })) });
  const cleanChannels = (cs: InstagramExploration['years'][number]['channels']) => ({ combined: cleanDetail(cs.combined), saved: cleanDetail(cs.saved), liked: cleanDetail(cs.liked) });
  const cleanPeriod = (p: InstagramExploration['years'][number]) => ({ ...p, channels: cleanChannels(p.channels) });
  return {
    schemaVersion: 1, sensitivity: 'low disclosure', warning: 'Ranked aggregate activity patterns can still reveal personal information. No guarantee of anonymity.',
    exportDate: data.exportDate, coverage: data.coverage, calendarTimezone: data.calendarTimezone, timeOfDayTimezone: data.timeOfDayTimezone, knownMonth: data.knownMonth,
    totals: data.totals, years: data.years.map(cleanPeriod), quarters: data.quarters.map(cleanPeriod), months: data.months.map(cleanPeriod), weekly: data.weekly,
    transition: data.transition, gaps: data.gaps, exactGaps: data.exactGaps, segments: data.segments.map(s => ({ ...s, channels: cleanChannels(s.channels) })), localTimeByYear: data.localTimeByYear, sessions: data.sessions,
    filing: { ...data.filing, collections: data.filing.collections.map(c => ({ rank: c.rank, createdAt: c.createdAt, updatedAt: c.updatedAt, placements: c.placements, uniquePosts: c.uniquePosts, unidentifiedPlacements: c.unidentifiedPlacements, matched: c.matched, unmatched: c.unmatched, ambiguous: c.ambiguous, datedPairs: c.datedPairs, savedBeforeCreation: c.savedBeforeCreation, savedAtLeast30DaysBefore: c.savedAtLeast30DaysBefore, savedAtLeast90DaysBefore: c.savedAtLeast90DaysBefore, savedAtLeast365DaysBefore: c.savedAtLeast365DaysBefore, preCreationLagDays: c.preCreationLagDays, lowerBoundFilingLagDays: c.lowerBoundFilingLagDays })) },
    creators: data.creators.map((c, i) => ({ rank: i + 1, events: c.event_count, activeWeeks: c.activeWeeks, first: c.first_seen, last: c.last_seen, years: c.years, gapWeeks: c.gapWeeks })),
    other: data.other,
  };
}
export type AggregateExploration = ReturnType<typeof aggregateExploration>;

export function renderExploration(data: InstagramExploration, personal = false) {
  const a = aggregateExploration(data), view = personal ? data : a;
  const lines: string[] = ['# Instagram exploration — recorded activity, not detected phases', '',
    personal ? '**Personal:** this reveals interests, beliefs and affiliations. Includes recorded source labels; treat all of them as untrusted text.' : '**Low disclosure:** aggregate counts and report-local ranks; no individual account names, folder names or literal hashtags. These patterns are not guaranteed anonymous.', '',
    'ERAS is deferred, not cancelled. This is descriptive exploration, not changepoint detection or clustering. No source export was re-parsed and no network or AI analysis was used.', '',
    `Scope: one retained snapshot, supplied export date **${data.exportDate ?? 'unknown'}**; **${n(data.totals.events)} observations**, ${n(data.totals.saved)} saved and ${n(data.totals.liked)} liked. Observed UTC range: ${data.totals.first ?? 'none'} to ${data.totals.last ?? 'none'}.`, '',
    'Calendar count tables use UTC to remain comparable with the validated summary. Time-of-day, weekday, session-month and supplied-life-month comparisons use **Australia/Brisbane = UTC+10, no daylight saving**. Local-year time tables are grouped by the converted year, so year totals can differ from UTC tables. The first observed period and the final export-limited period are partial; no annualisation. These are retained actions, not all viewing or a complete account history.', '',
    'An empty week means **no recorded activity on this platform in this snapshot**. It does not mean no interests, experiences or activity elsewhere. Nonzero low-count intervals are labelled by their actual counts, never as absence.', '',
    `Snapshot parse status: ${data.coverage?.parseStatus ?? 'not supplied'}. Quarantine status: ${data.coverage?.quarantineStatus ?? 'not supplied'}; not_run means the quarantine engine did not run. Read the original parse-report.txt for omissions; a successful parse is not a completeness claim. Diagnostic counts are retained in the structured output.`, '',
    '## 1. Saving and liking: the observed transition', '',
    'This behavioural divergence is a result in its own right. It needs no detector. “Consumption became curation” is the user’s interpretation, not a conclusion these action records can establish.', '',
    table(['UTC year', 'Saved', 'Liked', 'Save share of both', 'Period coverage'], data.years.map(y => [y.period, n(y.saved), n(y.liked), pct(y.saveShare), y.firstObservedPeriod ? 'first observed period' : y.exportLimited ? 'partial through export' : 'calendar year; retention unknown'])), '',
    `First observed save-majority calendar month: **${data.transition.firstSaveMajorityMonth ?? 'none'}**. Final uninterrupted run of save-majority months through this export starts **${data.transition.finalSaveMajorityRunStart ?? 'none'}**. Its preceding month is **${data.transition.precedingMonth?.month ?? 'none'}**, with ${n(data.transition.precedingMonth?.saved)} saves and ${n(data.transition.precedingMonth?.liked)} likes.`, '',
    'These are literal comparisons of monthly counts, not an estimated change date. The first majority month and the eventual uninterrupted run need not agree. A final month is censored; this does not predict continued dominance. Read the adjacent months as a transition window, not a day.', '',
    table(['UTC month', 'Saved', 'Liked', 'Larger observed count'], data.transition.months.map(m => [m.month, m.saved, m.liked, m.dominance])), '',
    '## 2. Low-count intervals and possible cross-platform comparisons', '',
    'No Instagram timestamp identifies a TikTok migration. The table dates the low-count intervals that can be compared with the user’s recollection. “Little” is an explicit counting convention: every week has 0–4 observations, for at least four consecutive Monday-starting UTC weeks. This is not a fitted threshold. Exact zero runs are listed separately. Endpoint weeks are excluded conservatively; apparent gaps may reflect incomplete retention.', '',
    table(['Start UTC', 'End UTC inclusive', 'Weeks', 'Recorded events', 'Empty weeks', 'Events/week max'], data.gaps.combined.atMostFour.map(g => [g.start, g.endInclusive, g.weeks, g.events, g.emptyWeeks, g.maximumPerWeek])), '',
    '**Exact zero runs of four or more weeks — no recorded activity on this platform:**', '',
    table(['Start UTC', 'End UTC inclusive', 'Weeks'], data.gaps.combined.zero.map(g => [g.start, g.endInclusive, g.weeks])), '',
    '**Every inter-observation gap of at least 28 elapsed days:** this additional check catches gaps not aligned to Mondays. The endpoints themselves are recorded observations; the open interval between them has no recorded activity on this platform. It is not a claim about activity before the first or after the last observation.', '',
    table(['Preceding observation UTC', 'Next observation UTC', 'Elapsed days'], data.exactGaps.combined.map(g => [g.precedingObservation, g.nextObservation, n(g.elapsedDays)])), '',
    'Four-week before/inside/after comparisons for every low-count interval are included below and in the structured file. A low interval containing some records cannot truthfully be called “no recorded activity.” Its zero subweeks have that description. Saved-only and liked-only runs are also retained in the structured output.', '',
    '## 3. Supplied life-event month and other before/after comparisons', '',
    `Supplied month: **${data.knownMonth ?? 'not supplied'}**. No exact departure day was supplied. The whole local month is kept separate; before ends at the start of that local month and after begins at the start of the next local month. Twelve-month flanks make unequal whole-history spans visible. No comparison establishes the cause of a difference.`, '',
    table(['Segment', 'UTC start inclusive', 'UTC end exclusive', 'Saved', 'Liked', 'Events', 'Unique creators', 'Requested window exceeds observed range'], data.segments.map(s => [s.label, s.start ?? 'first observation', s.endExclusive ?? 'last observation', s.channels.combined.saved, s.channels.combined.liked, s.channels.combined.events, s.channels.combined.knownCreators, s.extendsOutsideObservedRange ? 'yes' : 'no; completeness still unknown'])), '',
    'Composition of the supplied-month, folder and action-mix segments follows. Hashtag presence is not a topic inference. Complete low-count/flank compositions are in JSON.', '',
    table(['Segment', 'Channel', 'Events', 'With hashtags', 'Top three tags', '/reel/ /p/ /tv/ unknown'], view.segments.filter(s => !s.label.includes('low-count interval')).flatMap(s => (['saved', 'liked'] as const).map(c => { const r = s.channels[c]; return [s.label, c, r.events, r.withTags, r.hashtags.slice(0, 3).map(t => `${t.tag} (${t.count})`).join(', ') || 'none recorded', [r.formats.reel ?? 0, r.formats.p ?? 0, r.formats.tv ?? 0, r.formats.unknown ?? 0].join('/')]; }))), '',
    '## 4. Retained folders in creation order', '',
    'Creation times are recorded facts about these retained folders, not filing timestamps. The earliest surviving folder dates the earliest organising evidence here, not necessarily the first folder ever used. No collection membership is projected backwards in time. Unidentified placements, if any, are counted separately in JSON rather than treated as distinct known posts.', '',
    table(['Folder', 'Creation UTC', 'Unique posts', 'Matched saved', 'Unmatched', 'Dated pairs', 'Saved before creation', 'At least 90 days earlier'], view.filing.collections.map(c => [personal ? `${c.rank}: ${'name' in c ? c.name : ''}` : `F${String(c.rank).padStart(2, '0')}`, c.createdAt, c.uniquePosts, c.matched, c.unmatched, c.datedPairs, c.savedBeforeCreation, c.savedAtLeast90DaysBefore])), '',
    '## 5. Filing backlog, folder sizes and overlap', '',
    `Of **${n(data.filing.savedObservations)} saved observations**, **${n(data.filing.matchedFiledObservations)}** match at least one retained folder, leaving **${n(data.filing.unfiledObservations)} without a matched placement**. There are ${n(data.filing.placementCount)} placements and ${n(data.filing.uniquePlacementPosts)} unique canonical placement posts. Subtracting all unique placement posts from saves is wrong when placements are unmatched. Ambiguous joins, if present, also cannot prove filing.`, '',
    `Age is elapsed time since saving, measured at the end of the supplied UTC export date (${data.filing.referenceExclusive ?? 'unknown'} exclusive). It is not time since filing or proof of being unsorted/abandoned. Unfiled age median **${n(data.filing.unfiledAgeDays.median)} days**, p90 **${n(data.filing.unfiledAgeDays.p90)}**, maximum **${n(data.filing.unfiledAgeDays.max)}**; dated denominator ${n(data.filing.unfiledAgeDays.n)}.`, '',
    table(['Save-age days [lower, upper)', 'Unfiled', 'Filed'], data.filing.unfiledAgeBins.map((b, i) => [`${b.daysFrom}–${b.daysToExclusive ?? 'unbounded'}`, b.count, data.filing.filedAgeBins[i].count])), '',
    table(['Save year UTC', 'All saves', 'No matched placement', 'Share'], data.filing.byYear.map(y => [y.year, y.saved, y.unfiled, pct(y.shareUnfiled)])), '',
    `Folder-size distribution (unique canonical posts): ${n(data.filing.collections.length)} folders, minimum ${n(data.filing.collectionSizes.min)}, median ${n(data.filing.collectionSizes.median)}, p90 ${n(data.filing.collectionSizes.p90)}, maximum ${n(data.filing.collectionSizes.max)}. Tiny does not mean abandoned.`, '',
    table(['Unique posts in folder', 'Folders'], data.filing.collectionSizeHistogram.sort((x, y) => Number(x.value) - Number(y.value)).map(r => [r.value, r.count])), '',
    `${n(data.filing.postsInMultipleFolders)} canonical posts occur in multiple folders. Top 15 folder pairs by distinct shared canonical posts; a post in three folders contributes to three pairs. Includes unmatched posts with valid identities; this measures folder overlap, not matched-save counts. Jaccard is shared / union.`, '',
    table(['Folder A', 'Folder B', 'Shared posts', 'Jaccard'], data.filing.overlap.slice(0, 15).map(r => [`F${String(r.a).padStart(2, '0')}`, `F${String(r.b).padStart(2, '0')}`, r.sharedPosts, pct(r.jaccard)])), '',
    '## 6. Retroactive filing: what creation dates can bound', '',
    `${n(data.filing.uniqueSavedPredatingAtLeastOneFolder)} unique matched saved observations predate at least one folder containing them. Across deduplicated post–folder pairs, ${n(data.filing.collections.reduce((s, c) => s + c.savedBeforeCreation, 0))} of ${n(data.filing.collections.reduce((s, c) => s + c.datedPairs, 0))} dated pairs predate creation; ${n(data.filing.collections.reduce((s, c) => s + c.savedAtLeast30DaysBefore, 0))} by at least 30 days, ${n(data.filing.collections.reduce((s, c) => s + c.savedAtLeast90DaysBefore, 0))} by at least 90 days and ${n(data.filing.collections.reduce((s, c) => s + c.savedAtLeast365DaysBefore, 0))} by at least a year. A post in multiple folders contributes once per folder here.`, '',
    'For a post saved before a folder existed, creation minus save time is a lower bound on the delay before placement in that folder. Actual filing may have happened later. For a post saved after creation, the lower bound is zero and the actual delay remains unknown. No filing-date distribution or historical folder membership can be recovered. Per-folder counts are above; lag quantiles and undated/unmatched coverage are in the structured output.', '',
    '## 7. Hashtags by year and behaviour', '',
    'Counts below are observations containing each exact exported hashtag, deduplicated within one observation; no case folding or caption extraction. Denominator is all events in that year/channel. Coverage is observations with at least one exported tag. Missing tags are not evidence of no topic. Raw token totals, full rankings and quarterly detail remain in the structured output.', '',
    personal ? 'Literal source tags are escaped as text; they are labels recorded in the export, not inferred topics.' : 'H-ranks substitute for all literal hashtags here, including tags that might name accounts. They are report-local ranks by whole-snapshot frequency. The personal file contains the actual tags, allowing topic inspection without committing names.', '',
    table(['UTC year', 'Channel', 'Events', 'With tags', 'Coverage', 'Top five hashtag presences'], view.years.flatMap(y => (['saved', 'liked'] as const).map(c => { const r = y.channels[c]; return [y.period, c, r.events, r.withTags, pct(r.hashtagCoverage), r.hashtags.slice(0, 5).map(t => `${t.tag} (${t.count})`).join(', ') || 'none recorded']; }))), '',
    '## 8. Time of day and day of week in Brisbane', '',
    'Stored UTC timestamps are converted by adding exactly ten hours. Monday is weekday index 0; all 24 hourly bins and all seven weekday bins are provided below. The 09:00–15:00 weekday bin is a descriptive clock interval, not a claim about the user’s actual school timetable, holidays or attendance. Shares use all recorded events in the row, not all hours spent online.', '',
    table(['Local year', 'Channel', 'Events', 'Mon/Tue/Wed/Thu/Fri/Sat/Sun', 'Weekday 09–15 share', 'Hours 00 through 23'], data.localTimeByYear.flatMap(y => (['combined', 'saved', 'liked'] as const).map(c => { const r = y.channels[c]; return [y.year, c, r.n, r.weekdaysMondayFirst.join('/'), pct(r.weekday09to15Share), r.hours.join('/')]; }))), '',
    table(['Segment', 'Channel', 'Events', 'Mon/Tue/Wed/Thu/Fri/Sat/Sun', 'Weekday 09–15 share', 'Hours 00 through 23'], data.segments.filter(s => !s.label.includes('low-count interval')).flatMap(s => (['combined', 'saved', 'liked'] as const).map(c => { const r = s.channels[c].time; return [s.label, c, r.n, r.weekdaysMondayFirst.join('/'), pct(r.weekday09to15Share), r.hours.join('/')]; }))), '',
    'Time distributions for all low-count segments and their flanks are retained in JSON. School-related differences are observations to compare, not evidence of a cause.', '',
    '## 9. Once/twice versus repeated account observations', '',
    'No account is classified as friend, peer or professional creator. The primary count uses the account’s total frequency across this entire combined snapshot: 1–2 versus 3+ observations. The second column uses frequency within the displayed year/channel to expose dependence on this choice. Events without IDs are separate. Later observations affect the whole-snapshot category; neither category establishes a relationship.', '',
    table(['UTC year', 'Channel', 'Events', 'Global 1–2 events/share', 'Global 3+ events', 'Within-year/channel 1–2 events', 'Unknown IDs'], data.years.flatMap(y => (['combined', 'saved', 'liked'] as const).map(c => { const r = y.channels[c]; return [y.period, c, r.events, `${r.globalOnceOrTwiceEvents} / ${pct(r.events ? r.globalOnceOrTwiceEvents / r.events : null)}`, r.globalThreePlusEvents, r.withinPeriodOnceOrTwiceEvents, r.unknownCreatorEvents]; }))), '',
    'Recurring accounts below means observed in at least two distinct UTC weeks, not necessarily an actual return after absence. First/last are first/last retained observations. All consecutive observed-week gaps are in the structured file; they never establish unfollowing, deletion or loss of interest.', '',
    table(['Account rank', 'Events', 'Active weeks', 'First observed UTC', 'Last observed UTC'], data.creators.filter(c => c.activeWeeks >= 2).slice(0, 15).map(c => [personal ? c.creator_id : `R${data.creators.indexOf(c) + 1}`, c.event_count, c.activeWeeks, c.first_seen, c.last_seen])), '',
    'Cross-export account absence is **not evaluated by this one-snapshot report**. A second retained, independently dated export is required. Two imports of the same observation bytes are not longitudinal evidence. “Absent from another export” would not mean an account vanished from Instagram.', '',
    '## 10. Recorded URL formats over time', '',
    'These are /reel/, /p/ and /tv/ URL shapes retained in post extras. /p/ is not proof of a photo: it may include a carousel or video. Therefore the snapshot cannot supply a reliable photo-versus-video split, and format counts cannot date when the platform itself changed.', '',
    table(['UTC year', 'Channel', '/reel/', '/p/', '/tv/', 'Unknown', 'Denominator'], data.years.flatMap(y => (['saved', 'liked'] as const).map(c => { const r = y.channels[c]; return [y.period, c, r.formats.reel ?? 0, r.formats.p ?? 0, r.formats.tv ?? 0, r.formats.unknown ?? 0, r.events]; }))), '',
    table(['Channel', '/tv/ observations', 'First recorded /tv/', 'Last recorded /tv/'], data.other.tvDates.map(t => [t.channel, t.events, t.first ?? 'none', t.last ?? 'none'])), '',
    'The last recorded /tv/ action dates only this export’s evidence, not discontinuation of IGTV or the date content was posted.', '',
    '## 11. Sessions: timestamp groupings, not decisions', '',
    'Primary grouping splits when the gap from the immediately preceding observation is **greater than 30 minutes**. This is a declared operational convention for separating bursts, not an inferred behavioural boundary or a validated attention measure. Equality remains in one group; chaining can create a long session. Fifteen and sixty minutes show sensitivity. A group does not prove one sitting or one decision, and its first-to-last span is not time spent viewing.', '',
    table(['Channel', 'Gap minutes', 'Sessions', 'One-event sessions', 'Mean events', 'Median', 'p90', 'Max'], data.sessions.map(s => [s.channel, s.gapMinutes, s.sessionCount, s.singleEventSessions, n(s.eventsPerSession.mean), n(s.eventsPerSession.median), n(s.eventsPerSession.p90), n(s.eventsPerSession.max)])), '',
    'Sessions are built on the full chronological stream before reporting periods. Session counts and all their events are assigned to the local month/year of the session’s first event; cross-boundary sessions can therefore differ from event-month totals. Combined sessions can contain both actions; separate-channel sessions can span events on the other channel and are not additive.', '',
    table(['Local year of session start', 'Channel', '30-minute sessions', 'Events in those sessions', 'Mean size', 'Median', 'p90', 'Max'], data.sessions.filter(s => s.gapMinutes === 30).flatMap(s => s.years.map(y => [y.period, s.channel, y.sessions, y.events, n(y.eventsPerSession.mean), n(y.eventsPerSession.median), n(y.eventsPerSession.p90), n(y.eventsPerSession.max)]))), '',
    '## 12. Calendar quarters and monthly session counts', '',
    table(['UTC quarter', 'Saved', 'Liked', 'Save share', 'Coverage'], data.quarters.map(q => [q.period, q.saved, q.liked, pct(q.saveShare), q.firstObservedPeriod ? 'first observed period' : q.exportLimited ? 'partial' : 'calendar period; retention unknown'])), '',
    table(['Month', 'UTC saved events', 'UTC liked events', 'Combined sessions 15/30/60 min, local start month'], data.months.map(m => [m.period, m.saved, m.liked, [15, 30, 60].map(g => data.sessions.find(s => s.channel === 'combined' && s.gapMinutes === g)!.months.find(x => x.period === m.period)?.sessions ?? 0).join('/')])), '',
    'All monthly per-channel session counts and size distributions, for all three gap settings, are included in the structured file. Zero-count calendar periods remain present; periods after the export are not populated with zeros.', '',
    '## 13. Other recorded structure and hard limits', '',
    `${data.other.bothActionsSamePost} canonical posts have both a saved and a liked observation. For these posts, ${data.other.savedAfterLike} saves follow the like, ${data.other.savedBeforeLike} precede it and ${data.other.sameTimestamp} have equal timestamps. Save-minus-like lag median ${n(data.other.likeToSaveDays.median)} days; denominator ${data.other.likeToSaveDays.n}. These are two recorded actions, not two views or duplicate imports.`, '',
    `${data.other.timestampCollisions.length} exact UTC timestamps contain multiple observations; maximum multiplicity ${data.other.timestampCollisions[0]?.count ?? 1}. Ties are kept, not assigned invented timing or causal order.`, '',
    'This snapshot cannot establish TikTok/YouTube activity, viewing time, attention, motives, actual friendships, why an account is absent, historical folder membership, actual filing dates, original post publication dates, complete photo/video media types, or the beginning/end of an interest. It cannot distinguish no activity from export omission, changed retention, unsaving or other missing observations. It cannot establish that twenty actions were one decision. Folder creation dates are precise for the retained folder objects only. These limits do not become solvable by naming calendar intervals “eras.”', '',
    'ERAS remains on the shelf. This report neither passes nor fails that experiment; no changepoint scores, clustering or inferred phase labels were produced.', '',
  ];
  return lines.join('\n');
}
