import { canonicalInstagramPostUrl } from './parsers/instagram-url.ts';
import type { proposeSplit, auditFolders, SplitPost } from './folder-split.ts';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const percent=(n:number)=>(n*100).toFixed(1)+'%';
const detail=(title:string,value:unknown)=>`<details><summary>${esc(title)}</summary><pre>${esc(JSON.stringify(value,null,2))}</pre></details>`;
export function splitPage(title:string,body:string){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>${esc(title)}</title><style>body{max-width:1100px;margin:40px auto;padding:0 24px;font:16px/1.55 system-ui;background:#f6f4ee;color:#253b36}h1,h2{font-family:Georgia,serif}section{border-top:2px solid #b7c3b7;padding:20px 0}article{background:white;border:1px solid #ccd4ca;margin:15px 0;padding:20px}summary,a{color:#236759}summary{cursor:pointer}table{border-collapse:collapse;width:100%}td,th{text-align:left;padding:8px;border-bottom:1px solid #ddd}pre{white-space:pre-wrap;overflow-wrap:anywhere}.notice{padding:15px;background:#fff0d9}li{margin:7px 0}@media print{body{margin:0}article{break-inside:avoid}}</style></head><body><h1>${esc(title)}</h1><p class="notice">Personal: contains folder names, creator IDs and post links. Proposals only; no assignments have changed. Links open Instagram only when you choose them.</p>${body}</body></html>`;}
function link(p:SplitPost){const parsed=p.url?canonicalInstagramPostUrl(p.url):null;return parsed?`<a href="${esc('https://www.instagram.com/'+parsed.postType+'/'+parsed.shortcode+'/')}" target="_blank" rel="noreferrer noopener">${esc(p.key)}</a>`:`${esc(p.key)} — no usable post link`;}
export function proposalHtml(p:ReturnType<typeof proposeSplit>){
  const cost=(c:typeof p.totals.strongOnly)=>`<p>${c.removals} posts removed from the target, ${c.additions} additions elsewhere, ${c.removalOnly} already in the destination; ${c.creatorDecisions} creator decisions/searches; ${c.newFolders} new folders. Estimated <strong>${c.estimatedClicks.low}–${c.estimatedClicks.high} clicks</strong> under the assumptions below.</p>`;
  let html=`<p>Folder ID: ${esc(p.target.id)} · ${p.target.posts} identifiable posts · ${p.target.unknownPlacements} placements without a usable post identity (leave in place).</p><p>Ranked by posts moved per creator decision. Each post still requires manual work. If reviewing several target folders, their proposals are independent: check shared posts and destinations before combining them; do not simply add click totals. Strong filing evidence is not a guarantee of topic fit.</p><h2>Strong suggestions only</h2>${cost(p.totals.strongOnly)}<h2>If you also accept every session group</h2>${cost(p.totals.allOptional)}<p class="notice">Click assumptions: 4–8 per add+remove, 2–4 per removal-only, 2–4 per creator search, 3–6 per new folder. Not measured against Instagram's current interface. Scrolling, finding posts, login and unavailable links add unknown work. Check each destination before removing from this folder.</p>`;
  if(!p.proposals.length)html+='<p>No supported split groups. The leave-in-place list is the result.</p>';
  for(const [i,g] of p.proposals.entries()){
    html+=`<section><h2>${i+1}. ${esc(g.name)}</h2><p>${esc(g.type)} · ${g.posts} posts / ${g.rows.length} creator decisions = <strong>${g.postsPerDecision.toFixed(1)} posts per decision</strong>.</p>${cost(g.cost)}<p>Observed hashtag labels: ${g.labels.ranked.length?g.labels.ranked.map(t=>esc(t.tag)).join(' · '):'No supported hashtag name'}. Hashtags on ${g.labels.tagged}/${g.labels.posts} posts (${percent(g.labels.coverage)})${g.labels.weakCoverage?' — weak hashtag coverage':''}.</p>${detail('Label evidence and exact counts',g.labels)}`;
    if(g.type==='session review')html+='<p class="notice">Review group only: repeated saving together does not prove a common topic. Creator IDs above are observed labels, not an invented topic name. Isolated residue creators remain in place.</p>';
    for(const c of g.rows){html+=`<article><h3>${esc(c.creator)} · ${c.posts.length} posts</h3><p>Destination: ${g.destination?esc(g.name):'A new folder, only if you decide this group belongs together'}. Other-folder evidence: ${c.full.externalPosts} distinct posts; largest weighted share ${percent(c.full.topShare)}. Excluding target posts: ${c.independent.externalPosts} distinct posts.</p><details><summary>Post checklist (${c.posts.length})</summary><ul>${c.posts.map(post=>`<li>${link(post)} — ${g.destination&&post.folders.includes(g.destination)?'Already in destination: remove from target only if approved.':'If approved: add to destination, then remove from target.'}</li>`).join('')}</ul></details>${detail('Creator counts in every other folder, including same-post corroboration',c.otherFolders)}${detail('Weighted concentration and target-excluded check',{full:c.full,independent:c.independent})}</article>`;}html+='</section>';
  }
  html+=`<section><h2>Leave in place for now · ${p.stay.length} posts</h2><p>No supported move is proposed for these posts. Mixed or sparse evidence does not prove a creator is inherently general.</p>`;
  for(const creator of [...new Set(p.stay.map(post=>post.creator))]){const rows=p.stay.filter(post=>post.creator===creator),c=p.creators.find(c=>c.creator===creator);html+=`<article><h3>${esc(creator??'No unambiguous creator match')} · ${rows.length}</h3><p>${esc(c?.status??'Unmatched or ambiguous in this snapshot')} — stay in target.</p><details><summary>Post links and stay flags</summary><ul>${rows.map(post=>`<li>${link(post)} — stay in place (${esc(post.status)}).</li>`).join('')}</ul></details>${c?detail('Creator evidence',{full:c.full,independent:c.independent,otherFolders:c.otherFolders,unfiledSaves:c.unfiledSaves}):''}</article>`;}
  html+=`</section>${detail('Repeated session edges (including edges across proposed groups)',p.residueEdges)}${detail('Fixed rules',p.rules)}<p>Evidence is from this snapshot only. Hashtag labels use the prespecified support gates and smoothed log ratio; missing tags do not establish absent topics.</p>`;
  return splitPage('Split proposal: '+p.target.name,html);
}
export function auditHtml(a:ReturnType<typeof auditFolders>){let html=`<p>${a.folders.length} folders; ${a.uniqueFiledPosts} distinct identifiable filed posts; ${a.multiFolderPosts} posts in multiple folders.</p><p>A bin candidate needs ≥100 posts, creator concentration (HHI) ≤0.10 and hashtag diversity (normalised entropy) ≥0.80. Assessability also needs ≥90% creator coverage, ≥30% hashtag coverage, ≥20 tagged posts and ≥10 distinct tags. These are disclosed organisational heuristics, not proof of topic incoherence.</p><p>Merge review requires ≥10 shared posts, ≥50% Jaccard overlap and ≥50% coverage of each folder. Containment (≥5 shared, ≥80% of smaller folder) is reported separately and need not mean merge.</p><h2>Folder audit</h2><table><tr><th>Folder / ID</th><th>Posts</th><th>Creator HHI</th><th>Tag diversity / coverage</th><th>Finding</th><th>Only-folder residue</th></tr>`;
  for(const f of a.folders)html+=`<tr><td>${esc(f.name)}<br>${esc(f.id)}</td><td>${f.posts}${f.unknownPlacements?' + '+f.unknownPlacements+' unidentified':''}</td><td>${f.creatorHHI?.toFixed(3)??'Unknown'}</td><td>${f.hashtagEntropy?.toFixed(3)??'Unknown'} / ${percent(f.hashtagCoverage)}<br>${f.distinctTags} tags; ${f.taggedPosts} tagged posts</td><td>${f.bin?'Bin candidate':!f.binAssessable?'Insufficient coverage for bin test':'Does not meet bin rule'}${f.underFive?' · Under 5 posts':''}</td><td>${f.residuePosts}/${f.matchedPosts} (${percent(f.residueShare)})</td></tr>`;
  html+='</table><h2>Merge and containment review</h2>';const pairs=a.pairs.filter(p=>p.mergeReview||p.containmentReview);if(!pairs.length)html+='<p>No pairs meet the fixed overlap rules.</p>';
  for(const p of pairs)html+=`<p>${esc(p.aName)} + ${esc(p.bName)}: ${p.shared} shared posts; Jaccard ${percent(p.jaccard)}, coverage ${percent(p.aShare)} / ${percent(p.bShare)}. ${p.mergeReview?'Merge review candidate.':'Containment only; may be intentional nesting.'}</p>`;
  html+='<h2>Creators observed in only one folder in this snapshot</h2><p>This is not an all-time claim. Unfiled saves do not count as another folder.</p>';for(const f of a.folders)html+=detail(f.name+' — '+f.residuePosts+' posts',f.exclusiveCreators);
  return splitPage('All-folder filing audit',html+detail('All folder-pair metrics, including zero overlaps',a.pairs));}
