import {enrichTags,selectFolders,compareFolders} from './hashtag-taxonomy.ts';
import {taxonomyFiles,comparisonHtml} from './hashtag-taxonomy-report.ts';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {readExplorationSnapshot} from './exploration-command.ts';
import {verifySnapshot,inside} from './snapshots.ts';
import {hashtagIndex,tagTable,countTags,tagCoverage,hashtagRules} from './hashtag-audit.ts';
import {hashtagPage,htmlEscape,scopeFiles} from './hashtag-audit-report.ts';
export async function hashtagAuditCommand(args:string[],io:{stdout?:(s:string)=>void;stderr?:(s:string)=>void}={}){const out=io.stdout??console.log,err=io.stderr??console.error,flags=new Map<string,string>(),names:string[]=[];
 for(let i=0;i<args.length;i+=2){if(!['--snapshot','--output','--largest','--source-root','--folder','--compare'].includes(args[i])||!args[i+1]||args[i+1].startsWith('--')||(args[i]!=='--folder'&&flags.has(args[i]))){err('Use --snapshot <retained snapshot> --output <fresh directory> [--folder "name" (repeatable) | --largest 3] [--compare "name"] [--source-root <protected exports>].');return 2;}if(args[i]==='--folder')names.push(args[i+1]);else flags.set(args[i],args[i+1]);}
 if(!flags.has('--snapshot')||!flags.has('--output')||!/^[1-9]\d?$/.test(flags.get('--largest')??'3')||names.length&&flags.has('--largest')){err('Supply a retained snapshot, fresh output directory, and folder names or a largest-folder count (not both).');return 2;}
 try{const started=Date.now(),source=await fs.realpath(flags.get('--snapshot')!),requested=path.resolve(flags.get('--output')!),parent=await fs.realpath(path.dirname(requested)),output=path.join(parent,path.basename(requested));
 const protectedPaths=[source,await fs.realpath(fileURLToPath(new URL('../../..',import.meta.url)))];if(flags.has('--source-root'))protectedPaths.push(await fs.realpath(flags.get('--source-root')!));if(protectedPaths.some(p=>inside(p,output)))throw Error('Protected output');
 const retained=await readExplorationSnapshot(source),index=hashtagIndex(retained.events,retained.bundle),global=countTags(index.whole),folders=index.folders.map(f=>({id:f.id,name:f.name,counts:countTags(f.posts)}));
 let selected:typeof index.folders;let comparison:ReturnType<typeof compareFolders>|undefined;
 try{selected=names.length?selectFolders(index.folders,names):index.folders.slice(0,Number(flags.get('--largest')??3));if(flags.has('--compare')){const other=selectFolders(index.folders,[flags.get('--compare')!])[0];if(!selected.length||other.id===selected[0].id){err('Choose a different comparison folder from the first selected folder.');return 2;}comparison=compareFolders(selected[0],other,index.saved);if(!selected.some(f=>f.id===other.id))selected.push(other);}}catch(e){err(e instanceof Error?e.message:'Folder selection failed.');return 2;}
 const scopes=[...(!names.length?[{prefix:'whole',title:'Whole snapshot - saved and liked, unique posts',posts:index.whole},{prefix:'saved',title:'All saved posts',posts:index.saved},{prefix:'liked',title:'All liked posts',posts:index.liked}]:[]),...selected.map((f,i)=>({prefix:'folder-'+(i+1),title:f.name,posts:f.posts}))];
 await fs.mkdir(output);const summaries: {scope:string;posts:number;structured:number;merged:number;gained:number;captionOnlyVocabulary:number;structuredOnlyVocabulary:number;frequent:number;pairs:number;triples:number;top:{top:number;tagsAvailable:number;posts:number}[];noFrequent:number;noTags:number}[]=[];for(const scope of scopes){const data=tagTable(scope.posts,global,folders);const files=scopeFiles(scope.prefix,scope.title,data);for(const [name,text]of files)await fs.writeFile(path.join(output,name),text+'\n',{flag:'wx',mode:0o600});if(scope.prefix.startsWith('folder-')){const enriched=enrichTags(data,scope.title,index.whole,index.saved);for(const [name,text]of taxonomyFiles(scope.prefix,scope.title,enriched,data))await fs.writeFile(path.join(output,name),text+'\n',{flag:'wx',mode:0o600});}const c=data.coverage;summaries.push({scope:scope.prefix,posts:c.posts,structured:c.structuredPosts,merged:c.mergedPosts,gained:c.gainedPosts,captionOnlyVocabulary:c.captionOnlyVocabulary.length,structuredOnlyVocabulary:c.structuredOnlyVocabulary.length,frequent:data.frequentTags.length,pairs:data.pairs.length,triples:data.triples.length,top:data.topCoverage,noFrequent:data.noFrequentTagPosts,noTags:data.noTagPosts});}
 if(comparison){await fs.writeFile(path.join(output,'comparison-personal.json'),JSON.stringify(comparison,null,2),{flag:'wx',mode:0o600});await fs.writeFile(path.join(output,'comparison.html'),comparisonHtml(comparison),{flag:'wx',mode:0o600});}
 const after=await verifySnapshot(source);if(JSON.stringify(after)!==JSON.stringify(retained.manifest))throw Error('Snapshot changed');
 const observationCoverage={all:tagCoverage(index.observations),saved:tagCoverage(index.observations.filter(p=>p.channels.includes('saved'))),liked:tagCoverage(index.observations.filter(p=>p.channels.includes('liked')))};
 await fs.writeFile(path.join(output,'provenance.json'),JSON.stringify({snapshotId:retained.manifest.snapshotId,artifacts:retained.manifest.artifacts,rules:hashtagRules,selection:{names,compare:flags.get('--compare')??null,selected:selected.map(f=>({id:f.id,name:f.name}))},observationCoverage,summaries,elapsedSeconds:(Date.now()-started)/1000,peakRssMiB:process.resourceUsage().maxRSS/1024,sourcesUnchanged:true},null,2),{flag:'wx',mode:0o600});
 await fs.writeFile(path.join(output,'index.html'),hashtagPage('Hashtag counts and co-occurrence',`<p>Caption tags are merged with the structured field. No groups were formed first. Select a scope below. Folder pages lead with distinctiveness and retain raw ordering, source coverage, pairs and triples. Tables retain all qualifying rows on linked pages; JSON also contains every tag counted once or twice.</p>${comparison?'<p><a href="comparison.html">Cross-folder overlap and distinguishability</a></p>':''}<ul>${scopes.map((s,i)=>`<li><a href="${s.prefix}${s.prefix.startsWith('folder-')?'-taxonomy':''}.html">${htmlEscape(s.title)}</a>: ${summaries[i].posts} posts; tagged coverage ${summaries[i].structured} to ${summaries[i].merged}.</li>`).join('')}</ul><p>Whole-snapshot unique posts: ${index.whole.length}, from ${index.observations.length} saved/liked observations. Channel tables overlap; do not add them. Unmatched folder entries use their retained placement text and are disclosed in folder coverage; they are not silently added to the whole saved/liked scope. For matched folder entries the saved observation is the source, keeping its coverage comparable to the saved table.</p><p>The creator-based method had little repeated-account structure: the three target folders contained 553, 480 and 457 creators for 796, 667 and 517 posts. That is the reason it offered few large creator-level decisions. It was not a test of hashtag signal.</p><p><a href="provenance.json">Source hashes, observation-level coverage and exact rules</a></p>`),{flag:'wx',mode:0o600});out(JSON.stringify({summaries,elapsedSeconds:(Date.now()-started)/1000,peakRssMiB:process.resourceUsage().maxRSS/1024,output},null,2));return 0;
 }catch{err('Hashtag audit could not finish. Check snapshot integrity and choose a fresh writable output directory outside inputs and the repository. Sources were not changed; an incomplete output may remain.');return 1;}}
