import {countTags, type TagPost, type tagTable} from './hashtag-audit.ts';
export const taxonomyRules={broadSavedShare:0.10,candidateMinPosts:3,candidateMinLog2Ratio:2,candidateMaxSnapshotShare:0.005,baseline:'Whole snapshot of unique saved/liked posts, including the target; log2(((k_in+0.5)/(n_in+1))/((k_snapshot+0.5)/(n_snapshot+1))). Not an outside-only baseline or significance test.',nameMatching:'NFC lowercase; remove punctuation/spaces. Compare whole folder name and words of at least four characters, plus simple trailing-s and trailing-ing forms; exact match or one edit for strings at least five characters. These are review flags, not semantic synonyms.',engagement:['fyp','explore','explorepage','reels','trending','viralreels','viral','foryou','foryoupage']};
const compact=(s:string)=>s.normalize('NFC').toLowerCase().replace(/[^\p{L}\p{N}]/gu,'');
const forms=(s:string)=>[s,...(s.endsWith('s')&&s.length>=5?[s.slice(0,-1)]:[]),...(s.endsWith('ing')&&s.length>=7?[s.slice(0,-3)]:[])];
function oneEdit(a:string,b:string){if(Math.abs(a.length-b.length)>1)return false;let i=0,j=0,n=0;while(i<a.length&&j<b.length){if(a[i]===b[j]){i++;j++;continue;}if(++n>1)return false;if(a.length>=b.length)i++;if(b.length>=a.length)j++;}return n+(a.length-i)+(b.length-j)<=1;}
export function noiseReasons(tag:string,name:string,savedCount:number,savedTotal:number){const t=compact(tag),reasons:string[]=[];if(taxonomyRules.engagement.includes(t))reasons.push('engagement-list match');
 const words=name.normalize('NFC').toLowerCase().match(/[\p{L}\p{N}]+/gu)??[],names=[compact(name),...words.filter(w=>w.length>=4)].filter(Boolean).flatMap(forms);
 if(forms(t).some(t=>names.some(n=>t===n||Math.min(t.length,n.length)>=5&&oneEdit(t,n))))reasons.push('folder-name spelling match');
 if(savedTotal>0&&savedCount/savedTotal>=taxonomyRules.broadSavedShare)reasons.push('on at least 10% of all saves');return reasons;}
export function enrichTags(data:ReturnType<typeof tagTable>,folderName:string,whole:TagPost[],saved:TagPost[]){const global=countTags(whole),savedCounts=countTags(saved);
 const all=data.allTags.map(t=>{const k=global.get(t.tag)??0,logRatio=Math.log2(((t.posts+0.5)/(data.posts.length+1))/((k+0.5)/(whole.length+1))),flags=noiseReasons(t.tag,folderName,savedCounts.get(t.tag)??0,saved.length);return {...t,insideShare:data.posts.length?t.posts/data.posts.length:0,snapshotPosts:k,snapshotTotal:whole.length,snapshotShare:whole.length?k/whole.length:0,savedPosts:savedCounts.get(t.tag)??0,savedTotal:saved.length,logRatio,flags,candidate:t.posts>=3&&logRatio>=2&&whole.length>0&&k/whole.length<=0.005};});
 const ranked=all.filter(t=>t.posts>=3).sort((a,b)=>b.logRatio-a.logRatio||b.posts-a.posts||a.tag.localeCompare(b.tag)),flagged=new Set(all.filter(t=>t.flags.length).map(t=>t.tag));
 const coverage=(rows:typeof all)=>[10,25,50].map(top=>{const tags=new Set(rows.slice(0,top).map(t=>t.tag));return {top,tagsAvailable:tags.size,posts:data.posts.filter(p=>p.merged.some(t=>tags.has(t))).length};});
 const onlyFlagged=data.posts.filter(p=>p.merged.length>0&&p.merged.every(t=>flagged.has(t))),noTags=data.posts.filter(p=>!p.merged.length);
 return {rules:taxonomyRules,allTags:all,raw:all.filter(t=>t.posts>=3),distinctive:ranked,unflagged:ranked.filter(t=>!t.flags.length),flagged:all.filter(t=>t.flags.length),candidates:ranked.filter(t=>t.candidate&&!t.flags.length),flaggedCandidates:ranked.filter(t=>t.candidate&&t.flags.length),onlyFlaggedPostKeys:onlyFlagged.map(p=>p.key),noTags:noTags.length,effectivelyUntagged:onlyFlagged.length+noTags.length,coverage:{raw:coverage(all.filter(t=>t.posts>=3)),distinctive:coverage(ranked),unflaggedDistinctive:coverage(ranked.filter(t=>!t.flags.length))}};}
export function selectFolders<T extends {id:string;name:string}>(folders:T[],names:string[]){return names.map(name=>{const exact=folders.filter(f=>f.name.normalize('NFC').trim().toLowerCase()===name.normalize('NFC').trim().toLowerCase());const matches=exact.length?exact:compact(name)?folders.filter(f=>compact(f.name)===compact(name)):[];if(matches.length!==1)throw Error(matches.length?'Folder name is ambiguous; use an exact unique name.':'Folder name not found.');return matches[0];}).filter((f,i,all)=>all.findIndex(x=>x.id===f.id)===i);}
function distributions(a:TagPost[],b:TagPost[],excluded:Set<string>,frequentOnly:boolean){let ca=countTags(a),cb=countTags(b);const keys=[...new Set([...ca.keys(),...cb.keys()])].filter(t=>!excluded.has(t)&&(!frequentOnly||(ca.get(t)??0)+(cb.get(t)??0)>=3));const na=keys.reduce((n,t)=>n+(ca.get(t)??0),0),nb=keys.reduce((n,t)=>n+(cb.get(t)??0),0);if(!na||!nb)return {assessable:false,jsdBits:null,sharedMass:null,tags:keys.length,taggedA:a.filter(p=>p.merged.some(t=>keys.includes(t))).length,taggedB:b.filter(p=>p.merged.some(t=>keys.includes(t))).length,incidencesA:na,incidencesB:nb};
 let jsd=0,overlap=0;for(const t of keys){const p=(ca.get(t)??0)/na,q=(cb.get(t)??0)/nb,m=(p+q)/2;if(p)jsd+=0.5*p*Math.log2(p/m);if(q)jsd+=0.5*q*Math.log2(q/m);overlap+=Math.min(p,q);}const allowed=new Set(keys);return {assessable:true,jsdBits:jsd,sharedMass:overlap,tags:keys.length,taggedA:a.filter(p=>p.merged.some(t=>allowed.has(t))).length,taggedB:b.filter(p=>p.merged.some(t=>allowed.has(t))).length,incidencesA:na,incidencesB:nb};}
export function compareFolders(a:{id:string;name:string;posts:TagPost[]},b:{id:string;name:string;posts:TagPost[]},saved:TagPost[]){const ca=countTags(a.posts),cb=countTags(b.posts),cs=countTags(saved),sharedKeys=new Set(a.posts.filter(p=>b.posts.some(q=>p.key===q.key)).map(p=>p.key));const flags=new Set([...new Set([...ca.keys(),...cb.keys()])].filter(t=>noiseReasons(t,a.name,cs.get(t)??0,saved.length).length||noiseReasons(t,b.name,cs.get(t)??0,saved.length).length));
 const sharedTags=[...ca.keys()].filter(t=>cb.has(t)).map(tag=>({tag,a:ca.get(tag)!,b:cb.get(tag)!,aShare:ca.get(tag)!/a.posts.length,bShare:cb.get(tag)!/b.posts.length,flags:[...new Set([...noiseReasons(tag,a.name,cs.get(tag)??0,saved.length),...noiseReasons(tag,b.name,cs.get(tag)??0,saved.length)])]})).sort((x,y)=>(y.a+y.b)-(x.a+x.b)||x.tag.localeCompare(y.tag));
 const variant=(aa:TagPost[],bb:TagPost[])=>({aPosts:aa.length,bPosts:bb.length,all:distributions(aa,bb,new Set(),false),withoutFlagged:distributions(aa,bb,flags,false),withoutFlaggedRepeated:distributions(aa,bb,flags,true)});
 return {a:{id:a.id,name:a.name,posts:a.posts.length,tagged:a.posts.filter(p=>p.merged.length).length},b:{id:b.id,name:b.name,posts:b.posts.length,tagged:b.posts.filter(p=>p.merged.length).length},sharedPosts:a.posts.filter(p=>sharedKeys.has(p.key)),postJaccard:sharedKeys.size/(a.posts.length+b.posts.length-sharedKeys.size||1),sharedTags,excludedTags:[...flags].sort(),withSharedPosts:variant(a.posts,b.posts),withoutSharedPosts:variant(a.posts.filter(p=>!sharedKeys.has(p.key)),b.posts.filter(p=>!sharedKeys.has(p.key))),interpretation:'Jensen-Shannon divergence ranges from 0 (same normalised tag-incidence distribution) to 1 (disjoint); shared mass ranges from 0 to 1 in the opposite direction. These are descriptive distributions, not held-out classification accuracy or proof that the taxonomy is arbitrary. Untagged posts are not represented in the tag distributions. Rare tags can inflate separation; compare the repeated-tag and shared-post-excluded versions.'};}
