import type { tagTable } from './hashtag-audit.ts';
import { hashtagRules } from './hashtag-audit.ts';
import { canonicalInstagramPostUrl } from './parsers/instagram-url.ts';
export const htmlEscape=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function hashtagPage(title:string,body:string){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>${htmlEscape(title)}</title><style>body{max-width:1250px;margin:30px auto;padding:0 24px;background:#f6f4ee;color:#253b36;font:16px/1.55 system-ui}h1,h2{font-family:Georgia,serif}table{width:100%;border-collapse:collapse}td,th{padding:8px;text-align:left;border-bottom:1px solid #ccd4ca;vertical-align:top}a,summary{color:#236759}summary{cursor:pointer}pre{white-space:pre-wrap;overflow-wrap:anywhere}.notice{background:#fff0d9;padding:15px}nav{padding:15px 0;display:flex;gap:15px;flex-wrap:wrap}small{font-size:13px}@media print{body{background:white}}</style></head><body><p><a href="index.html">All scopes</a></p><h1>${htmlEscape(title)}</h1><p class="notice">Personal: contains tags, folder identities and post links. Counts only: no proposed names, clustering or assignments. Nothing opens Instagram unless you click a post link.</p>${body}</body></html>`;}
const pct=(n:number,d:number)=>d?(100*n/d).toFixed(2)+'%':'not available';
export function* scopeFiles(prefix:string,title:string,data:ReturnType<typeof tagTable>){const c=data.coverage;
 const urls=new Map(data.posts.map(p=>[p.key,p.url]));
 const links=(keys:string[])=>`<details><summary>${keys.length} post links</summary><ul>${keys.map(k=>{const url=urls.get(k),p=url?canonicalInstagramPostUrl(url):null;return `<li>${p?`<a href="https://www.instagram.com/${p.postType}/${p.shortcode}/" target="_blank" rel="noopener noreferrer">${htmlEscape(k)}</a>`:htmlEscape(k)+' - no usable URL'}</li>`;}).join('')}</ul></details>`;
 const pageNav=(kind:string,page:number,pages:number)=>`<nav><a href="${prefix}.html">Scope summary</a>${page>0?`<a href="${prefix}-${kind}-${page}.html">Previous</a>`:''}<span>Page ${page+1} of ${pages}</span>${page+1<pages?`<a href="${prefix}-${kind}-${page+2}.html">Next</a>`:''}</nav>`;
 function* paginate<T>(kind:string,rows:T[],headers:string[],render:(r:T)=>string){const size=500,pages=Math.max(1,Math.ceil(rows.length/size));for(let page=0;page<pages;page++){const nav=pageNav(kind,page,pages);yield [`${prefix}-${kind}-${page+1}.html`,hashtagPage(title+' - '+kind,`<p>${rows.length} rows total; every row is retained. Ordered by post count, then tag spelling. Pages are a display convenience, not a count cutoff.</p>${nav}<table><tr>${headers.map(h=>'<th>'+h+'</th>').join('')}</tr>${rows.slice(page*size,(page+1)*size).map(render).join('')}</table>${nav}`)] as const;}}
 yield* paginate('tags',data.frequentTags,['Hashtag','Posts pulled out','Clean posts','Co-tags (all / repeated)','Whole-snapshot posts','Other evidence'],t=>`<tr><td>${htmlEscape(t.tag)}</td><td>${t.posts}</td><td>${t.cleanPosts}</td><td>${t.coTagPartners} / ${t.repeatedCoTagPartners}</td><td>${t.wholeSnapshotPosts}</td><td>${links(t.postKeys)}<details><summary>Counts in ${t.folders.length} folders</summary>${t.folders.map(f=>`<p>${htmlEscape(f.name)}: ${f.posts}</p>`).join('')}</details></td></tr>`);
 for(const kind of ['pairs','triples'] as const)yield* paginate(kind,data[kind],['Combination','Posts together','Share of each tag’s posts','Links'],r=>`<tr><td>${r.tags.map(htmlEscape).join(' + ')}</td><td>${r.posts}</td><td>${r.sharesOfEachTag.map(n=>(n*100).toFixed(1)+'%').join(' / ')}</td><td>${links(r.postKeys)}</td></tr>`);
 const countRows=[['Posts in this scope',c.posts],['Posts with a retained caption',`${c.captionPresent} (${pct(c.captionPresent,c.posts)})`],['Structured field alone',`${c.structuredPosts} (${pct(c.structuredPosts,c.posts)})`],['After adding all caption tags',`${c.mergedPosts} (${pct(c.mergedPosts,c.posts)})`],['Newly covered posts',c.gainedPosts],['Covered only by alternate caption values',c.alternateOnlyCoveragePosts],['Distinct tags only in structured source',c.structuredOnlyVocabulary.length],['Distinct tags only in caption source',c.captionOnlyVocabulary.length],['Distinct tags in both sources',c.sharedVocabulary.length],['Post-tag incidences only in structured source',c.structuredOnlyPostTagIncidences],['Post-tag incidences only in caption source',c.captionOnlyPostTagIncidences],['Tag incidences only in alternate caption values',c.alternateOnlyPostTagIncidences],['Structured values outside caption grammar (retained)',c.invalidStructuredValues.length],['Unmatched/ambiguous saved join (placement evidence only)',c.unmatchedPosts],['No canonical post identity (counted by record ID)',c.unknownIdentityPosts]];
 yield [prefix+'.html',hashtagPage(title,`<h2>Source coverage</h2><table>${countRows.map(([a,b])=>`<tr><th>${a}</th><td>${b}</td></tr>`).join('')}</table><p>Distinct vocabulary counts and post-tag incidences answer different questions: the same tag can appear in both sources overall while being missing from one source on particular posts.</p><h2>Counted lists</h2><nav><a href="${prefix}-tags-1.html">Every hashtag on 3+ posts (${data.frequentTags.length})</a><a href="${prefix}-pairs-1.html">Repeated pairs (${data.pairs.length})</a><a href="${prefix}-triples-1.html">Repeated triples (${data.triples.length})</a><a href="${prefix}-personal.json">Full JSON, including tags on 1–2 posts</a></nav><p>Clean means the post carries no other tag appearing on 3+ posts in this scope. It may carry rarer tags. This is a count, not a recommendation to move. Co-tag partners count distinct companions; repeated companions share at least two posts. Broad co-occurrence is visible without assigning a generic/topic label.</p><h2>Union coverage, without double-counting posts</h2><table><tr><th>Leading frequent tags</th><th>Covered</th><th>Not covered by that set</th></tr>${data.topCoverage.map(r=>`<tr><td>Top ${r.top} (${r.tagsAvailable} available)</td><td>${r.posts} (${pct(r.posts,c.posts)})</td><td>${c.posts-r.posts}</td></tr>`).join('')}</table><p>${data.noFrequentTagPosts} posts carry no frequent tag at all; ${data.noTagPosts} of those carry no extracted/structured tag. ${data.noFrequentTagPosts-data.noTagPosts} carry only tags occurring once or twice. Overlapping pairs/triples are not additive and may reflect pasted tag bundles.</p><details><summary>Source-only tag vocabularies and unusual structured values</summary><pre>${htmlEscape(JSON.stringify({structuredOnly:c.structuredOnlyVocabulary,captionOnly:c.captionOnlyVocabulary,structuredOutsideCaptionGrammar:c.invalidStructuredValues},null,2))}</pre></details><details><summary>Exact extraction and counting rules</summary><pre>${htmlEscape(JSON.stringify(hashtagRules,null,2))}</pre></details>`)] as const;
 yield [prefix+'-personal.json',JSON.stringify(data)] as const;
}
